### Lest all messages
GET http://localhost:3000/messages


### Create a new msssage
Post http://localhost:3000/messages
content-type: application/json

{
    "content": "sdfsdf"
}


### Get a particular message
Get http://localhost:3000/messages/123123123
